-- https://school.programmers.co.kr/learn/courses/30/lessons/131124

-- 코드를 입력하세요
WITH t AS
(SELECT COUNT(REVIEW_ID) AS cc
FROM REST_REVIEW 
GROUP BY MEMBER_ID)

SELECT
m.MEMBER_NAME,
r.REVIEW_TEXT,
DATE_FORMAT(r.REVIEW_DATE, "%Y-%m-%d")
FROM REST_REVIEW r
LEFT JOIN MEMBER_PROFILE m
ON (r.MEMBER_ID = m.MEMBER_ID)
WHERE m.MEMBER_NAME IN (
SELECT
m.MEMBER_NAME
FROM REST_REVIEW r
LEFT JOIN MEMBER_PROFILE m
ON (r.MEMBER_ID = m.MEMBER_ID)
GROUP BY r.MEMBER_ID HAVING COUNT(r.REVIEW_ID) IN(
    SELECT MAX(t.cc)
    FROM t
)
)
ORDER BY r.REVIEW_DATE ASC, r.REVIEW_TEXT ASC