-- https://school.programmers.co.kr/learn/courses/30/lessons/131534

-- 코드를 입력하세요
WITH t AS (
SELECT
YEAR(SALES_DATE) AS YEAR,
MONTH(SALES_DATE) AS MONTH,
COUNT(DISTINCT USER_ID) AS PUCHASED_USERS
FROM ONLINE_SALE
WHERE USER_ID IN (
SELECT
USER_ID
FROM USER_INFO
WHERE JOINED LIKE "2021%")
GROUP BY YEAR, MONTH)

SELECT
t.YEAR,
t.MONTH,
t.PUCHASED_USERS,
ROUND(t.PUCHASED_USERS/(SELECT
COUNT(USER_ID)
FROM USER_INFO
WHERE JOINED LIKE "2021%"),1) AS PUCHASED_RATIO
FROM t
ORDER BY YEAR, MONTH