-- https://school.programmers.co.kr/learn/courses/30/lessons/151141
-- 코드를 입력하세요
WITH ft AS (
SELECT
h.HISTORY_ID,
DAILY_FEE,
DATEDIFF(h.END_DATE, h.START_DATE) + 1 AS DAY
FROM CAR_RENTAL_COMPANY_CAR c
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
ON (c.CAR_ID = h.CAR_ID)
WHERE c.CAR_TYPE = "트럭")

SELECT
ft.HISTORY_ID,
CASE
    WHEN ft.DAY < 7 THEN ft.DAILY_FEE * ft.DAY
    WHEN ft.DAY < 30 THEN FLOOR(ft.DAILY_FEE * ft.DAY * (100 - (SELECT
DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
WHERE d.CAR_TYPE = "트럭" AND DURATION_TYPE = "7일 이상")) / 100)
    WHEN ft.DAY < 90 THEN FLOOR(ft.DAILY_FEE * ft.DAY * (100 - (SELECT
DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
WHERE d.CAR_TYPE = "트럭" AND DURATION_TYPE = "30일 이상")) / 100)
    ELSE FLOOR(ft.DAILY_FEE * ft.DAY * (100 - (SELECT
DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
WHERE d.CAR_TYPE = "트럭" AND DURATION_TYPE = "90일 이상")) / 100)
END AS FEE
FROM ft
ORDER BY 2 DESC, 1 DESC