-- https://school.programmers.co.kr/learn/courses/30/lessons/144856
-- 코드를 입력하세요
WITH bb AS
(SELECT
 b.BOOK_ID,
 b.AUTHOR_ID,
 b.CATEGORY,
 b.PRICE * SUM(s.SALES) AS PP
 FROM BOOK b
 JOIN BOOK_SALES s ON (b.BOOK_ID = s.BOOK_ID)
 WHERE s.SALES_DATE LIKE "2022-01%"
 GROUP BY b.BOOK_ID
)

SELECT
a.AUTHOR_ID,
a.AUTHOR_NAME,
bb.CATEGORY,
SUM(bb.PP) AS TOTAL_SALES
FROM AUTHOR a
LEFT JOIN bb ON (a.AUTHOR_ID = bb.AUTHOR_ID)
GROUP BY a.AUTHOR_ID, bb.CATEGORY
ORDER BY a.AUTHOR_ID ASC, bb.CATEGORY DESC
